### PR TITLE
Remove credentials for Watson Speech to Text

### PR DESCRIPTION
**Pull request by arlemi**

### CODE REVIEW

**Review by stevemar — APPROVED** [review]
probably a good idea

**Comment by RK-Sharath** [comment]
@stevemart I have removed the credentials and submitted a PR for the same. Please review and merge.

**Comment by arlemi** [comment]
@RK-Sharath Your PR still has an API Key in it.

**Comment by RK-Sharath** [comment]
@arlemi Please advise where is it as i have removed the credentials.

**Comment by arlemi** [comment]
@RK-Sharath [Line 338](https://github.com/IBM/watson-nao-robot/blob/79bdf97baed19855d819424122d915aafbefa47d/choregraphe/watson_nao_robot/WatsonSTT/behavior.xar#L338) there's a Google API key for their speech-to-text service. You could have checked that by looking at my PR. 
Also you shouldn't merge your own pull requests without having someone else reviewing them.

**Comment by RK-Sharath** [comment]
@arlemi Thank you. I have submitted another PR for review.

**Comment by stevemar** [comment]
@arlemi thanks for the PR. I'll clean up the conflict and merge this one as it removes the google API key and the service uname/pass

**Review by stevemar — APPROVED** [review]
this matches the original PR, going to merge this one.

**Pull request merged**
